# Generated by Django 2.2.24 on 2021-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_areas', models.AutoField(db_column='ID_areas', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id_buildings', models.AutoField(db_column='ID_buildings', primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('builder', models.CharField(max_length=50)),
                ('urban_develop_zone', models.CharField(max_length=50)),
                ('all_rcvd_info', models.CharField(max_length=50)),
                ('parking', models.IntegerField()),
            ],
            options={
                'db_table': 'buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.AutoField(db_column='ID_customer', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('phone', models.CharField(db_column='Phone', max_length=15)),
                ('start_work', models.DateField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id_house', models.AutoField(db_column='ID_house', primary_key=True, serialize=False)),
                ('build_number', models.CharField(max_length=25)),
                ('street_type', models.CharField(max_length=50)),
                ('street_number', models.CharField(max_length=25)),
                ('ttl_area_building', models.FloatField()),
                ('ttl_area_apartments', models.FloatField()),
                ('storeys', models.IntegerField()),
                ('construction_phase', models.IntegerField()),
                ('construction_phase_prst', models.IntegerField()),
                ('parking_num', models.IntegerField()),
                ('parking_price_hrn', models.FloatField()),
                ('parking_price_dol', models.FloatField()),
                ('sales', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
                ('commis_year', models.DateField()),
                ('quarter', models.IntegerField(db_column='Quarter')),
            ],
            options={
                'db_table': 'houses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesAndPrices',
            fields=[
                ('id_row', models.AutoField(db_column='ID_row', primary_key=True, serialize=False)),
                ('a1_min_price', models.FloatField()),
                ('a1_max_price', models.FloatField()),
                ('a1_avg_price', models.FloatField()),
                ('a2_min_price', models.FloatField()),
                ('a2_max_price', models.FloatField()),
                ('a2_avg_price', models.FloatField()),
                ('a3_min_price', models.FloatField()),
                ('a3_max_price', models.FloatField()),
                ('a3_avg_price', models.FloatField()),
                ('a4_min_price', models.FloatField()),
                ('a4_max_price', models.FloatField()),
                ('a4_avg_price', models.FloatField()),
                ('a1_to_sale', models.IntegerField()),
                ('a2_to_sale', models.IntegerField()),
                ('a3_to_sale', models.IntegerField()),
                ('a4_to_sale', models.IntegerField()),
                ('a1_area_to_sale', models.FloatField()),
                ('a2_area_to_sale', models.FloatField()),
                ('a3_area_to_sale', models.FloatField()),
                ('a4_area_to_sale', models.FloatField()),
                ('area_remain', models.FloatField()),
                ('ondate', models.DateField()),
            ],
            options={
                'db_table': 'sales_and_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id_sections', models.AutoField(db_column='ID_sections', primary_key=True, serialize=False)),
                ('section_letter', models.CharField(max_length=50)),
                ('attribute', models.IntegerField()),
                ('financing', models.CharField(max_length=50)),
                ('duplex_apartments', models.IntegerField()),
                ('penthouses', models.IntegerField()),
                ('apartments_num', models.IntegerField()),
                ('a1_num', models.IntegerField()),
                ('a2_num', models.IntegerField()),
                ('a3_num', models.IntegerField()),
                ('a4_num', models.IntegerField()),
                ('a1_area_min', models.FloatField()),
                ('a1_area_max', models.FloatField()),
                ('a2_area_min', models.FloatField()),
                ('a2_area_max', models.FloatField()),
                ('a3_area_min', models.FloatField()),
                ('a3_area_max', models.FloatField()),
                ('a4_area_min', models.FloatField()),
                ('a4_area_max', models.FloatField()),
                ('avg_area', models.FloatField()),
                ('min_price_hrn', models.FloatField()),
                ('max_price_hrn', models.FloatField()),
                ('avg_price_hrn', models.FloatField()),
                ('min_price_dol', models.FloatField()),
                ('max_price_dol', models.FloatField()),
                ('avg_price_dol', models.FloatField()),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id_street', models.AutoField(db_column='ID_street', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'streets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subways',
            fields=[
                ('id_subway', models.AutoField(db_column='ID_subway', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'subways',
                'managed': False,
            },
        ),
    ]
