# Generated by Django 2.2.24 on 2021-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id_finance', models.AutoField(db_column='ID_finance', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('full_name', models.CharField(db_column='Full_name', max_length=50)),
            ],
            options={
                'db_table': 'financing',
                'managed': False,
            },
        ),
    ]
