# Generated by Django 2.2.24 on 2021-08-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210808_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='buildings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesandprices',
            options={},
        ),
        migrations.AlterModelOptions(
            name='streets',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subways',
            options={},
        ),
    ]
