# Generated by Django 2.2.24 on 2021-08-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210808_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='buildings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='financing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesandprices',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='streets',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subways',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='street_type',
        ),
    ]
