# Generated by Django 3.2.8 on 2021-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211008_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='build_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='commerc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='gps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='sell_center',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='total_area_complex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='type_complex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='quarter_start',
            field=models.IntegerField(blank=True, db_column='Quarter_start', null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
