# Generated by Django 2.2.24 on 2021-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_buildings_parking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='attribute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='duplex_apartments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='penthouses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
