# Generated by Django 3.2.8 on 2021-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211114_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
