# Generated by Django 2.2.24 on 2021-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210809_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='ownership',
            field=models.CharField(blank=True, db_column='Ownership', max_length=50, null=True),
        ),
    ]
