# Generated by Django 3.2.8 on 2021-11-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211114_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id_tech', models.AutoField(db_column='id_tech', primary_key=True, serialize=False)),
                ('frame', models.CharField(blank=True, max_length=500, null=True)),
                ('overlap', models.CharField(blank=True, max_length=500, null=True)),
                ('partitions', models.CharField(blank=True, max_length=500, null=True)),
                ('facade', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.CharField(blank=True, max_length=500, null=True)),
                ('heating', models.CharField(blank=True, max_length=500, null=True)),
                ('roof', models.CharField(blank=True, max_length=500, null=True)),
                ('terraces', models.CharField(blank=True, max_length=500, null=True)),
                ('ceilings', models.CharField(blank=True, max_length=500, null=True)),
                ('material', models.CharField(blank=True, max_length=500, null=True)),
                ('walls', models.CharField(blank=True, max_length=500, null=True)),
                ('warming', models.CharField(blank=True, max_length=500, null=True)),
                ('windows', models.CharField(blank=True, max_length=500, null=True)),
                ('manuf_windows', models.CharField(blank=True, max_length=500, null=True)),
                ('boiler', models.CharField(blank=True, max_length=500, null=True)),
                ('roofing', models.CharField(blank=True, max_length=500, null=True)),
                ('balconies', models.CharField(blank=True, max_length=500, null=True)),
                ('apartments', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
    ]
