# Generated by Django 2.2.24 on 2021-08-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customers_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_ownership', models.AutoField(db_column='id_ownership', primary_key=True, serialize=False)),
                ('form', models.CharField(blank=True, db_column='form', max_length=50, null=True)),
                ('full_form', models.CharField(blank=True, db_column='full_form', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ownership',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='customers',
            name='ownership',
            field=models.ForeignKey(blank=True, db_column='form', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ownership'),
        ),
    ]
