# Generated by Django 3.2.8 on 2021-11-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_technical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id_purp', models.AutoField(db_column='id_purp', primary_key=True, serialize=False)),
                ('social_facilities', models.CharField(blank=True, max_length=500, null=True)),
                ('playground', models.CharField(blank=True, max_length=500, null=True)),
                ('comfort', models.CharField(blank=True, max_length=500, null=True)),
                ('security', models.CharField(blank=True, max_length=500, null=True)),
                ('infrastructure', models.CharField(blank=True, max_length=500, null=True)),
                ('rest', models.CharField(blank=True, max_length=500, null=True)),
                ('halls', models.CharField(blank=True, max_length=500, null=True)),
                ('solutions', models.CharField(blank=True, max_length=500, null=True)),
                ('bicycle_parking', models.CharField(blank=True, max_length=500, null=True)),
                ('animals', models.CharField(blank=True, max_length=500, null=True)),
                ('access', models.CharField(blank=True, max_length=500, null=True)),
                ('storage', models.CharField(blank=True, max_length=500, null=True)),
                ('concierge', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('id_out', models.AutoField(db_column='id_out', primary_key=True, serialize=False)),
                ('entertainment', models.CharField(blank=True, max_length=500, null=True)),
                ('transport', models.CharField(blank=True, max_length=500, null=True)),
                ('school', models.CharField(blank=True, max_length=500, null=True)),
                ('kindergarten', models.CharField(blank=True, max_length=500, null=True)),
                ('shops', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id_land', models.AutoField(db_column='id_land', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('land_area', models.CharField(blank=True, max_length=500, null=True)),
                ('cadastral', models.CharField(blank=True, max_length=500, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('percentage', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id_fin', models.AutoField(db_column='id_fin', primary_key=True, serialize=False)),
                ('contribution', models.CharField(blank=True, max_length=500, null=True)),
                ('installment', models.CharField(blank=True, max_length=500, null=True)),
                ('mortgage', models.CharField(blank=True, max_length=500, null=True)),
                ('discount_100', models.CharField(blank=True, max_length=500, null=True)),
                ('discount', models.CharField(blank=True, max_length=500, null=True)),
                ('bank', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Additionally',
            fields=[
                ('id_add', models.AutoField(db_column='id_add', primary_key=True, serialize=False)),
                ('schemes', models.CharField(blank=True, max_length=500, null=True)),
                ('strengths', models.CharField(blank=True, max_length=500, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=500, null=True)),
                ('additional', models.CharField(blank=True, max_length=500, null=True)),
                ('id_buildings', models.ForeignKey(blank=True, db_column='ID_buildings', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buildings')),
            ],
        ),
    ]
