# Generated by Django 2.2.24 on 2021-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210810_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='start_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
