# Generated by Django 3.2.8 on 2021-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211125_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='Render',
            field=models.ImageField(default='Нет', upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='map',
            field=models.ImageField(default='Нет', upload_to='imgs'),
        ),
    ]
