# Generated by Django 2.2.24 on 2021-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210811_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildings',
            old_name='parking_price_dol',
            new_name='parking_price_dol_max',
        ),
        migrations.RenameField(
            model_name='buildings',
            old_name='parking_price_hrn',
            new_name='parking_price_dol_min',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='parking_price_dol',
            new_name='parking_price_dol_max',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='parking_price_hrn',
            new_name='parking_price_dol_min',
        ),
        migrations.AddField(
            model_name='buildings',
            name='parking_price_hrn_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='parking_price_hrn_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='parking_price_hrn_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='parking_price_hrn_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
