# Generated by Django 3.2.8 on 2021-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211125_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='guest_parking_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='storeys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='commerc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
