# Generated by Django 2.2.24 on 2021-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210822_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='nubmer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
