# Generated by Django 2.2.24 on 2021-08-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sections_nubmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='nubmer',
            new_name='number',
        ),
    ]
