# Generated by Django 3.2.8 on 2021-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211127_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionally',
            name='additional',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='additionally',
            name='schemes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='additionally',
            name='strengths',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='additionally',
            name='weaknesses',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='zone',
            field=models.CharField(blank=True, db_column='Zone', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='builder',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='class_field',
            field=models.CharField(blank=True, db_column='class', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='gps',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='grade',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='rating',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='type_complex',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='urban_develop_zone',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='bank',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='contribution',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='discount',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='discount_100',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='installment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='mortgage',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='financing',
            name='full_name',
            field=models.CharField(blank=True, db_column='Full_name', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='financing',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='commis_year',
            field=models.CharField(blank=True, db_column='commis_year', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='remark',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='start_year',
            field=models.CharField(blank=True, db_column='start_year', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='storeys',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='cadastral',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_area',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='percentage',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='purpose',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='info',
            field=models.CharField(blank=True, db_column='info', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='entertainment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='kindergarten',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='school',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='shops',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='transport',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='form',
            field=models.CharField(blank=True, db_column='form', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='full_form',
            field=models.CharField(blank=True, db_column='full_form', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='access',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='animals',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='bicycle_parking',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='comfort',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='concierge',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='halls',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='infrastructure',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='playground',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='rest',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='security',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='social_facilities',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='solutions',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='storage',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='attribute',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='duplex_apartments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='penthouses',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='streets',
            name='type',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='subways',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='subways',
            name='zone',
            field=models.CharField(blank=True, db_column='Zone', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='apartments',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='balconies',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='boiler',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='ceilings',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='facade',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='frame',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='heating',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='manuf_windows',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='material',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='overlap',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='partitions',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='profile',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='roof',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='roofing',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='terraces',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='walls',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='warming',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='windows',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
