# Generated by Django 3.2.8 on 2021-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211201_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandprices',
            name='month',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='year',
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
