# Generated by Django 2.2.24 on 2021-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210822_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
