# Generated by Django 2.2.24 on 2021-08-27 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210827_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id_log', models.AutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='form', max_length=2000, null=True)),
                ('time', models.DateTimeField(blank=True, db_column='full_form', default=datetime.datetime(2021, 8, 27, 13, 54, 51, 303764), null=True)),
            ],
            options={
                'db_table': 'logger',
                'managed': True,
            },
        ),
    ]
