# Generated by Django 3.2.8 on 2021-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211205_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandprices',
            name='date',
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
