# Generated by Django 2.2.24 on 2021-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time',
            field=models.DateTimeField(blank=True, db_column='time', default='2021-08-27 14:28:14', null=True),
        ),
    ]
