# Generated by Django 2.2.24 on 2021-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210827_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'managed': True, 'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='logger',
            name='time',
            field=models.DateTimeField(blank=True, db_column='time', default='2021-08-27 15:57:13', null=True),
        ),
    ]
