# Generated by Django 2.2.24 on 2021-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210827_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='logger',
            name='info',
            field=models.CharField(blank=True, db_column='info', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time',
            field=models.DateTimeField(blank=True, db_column='time', default='2021-08-27 16:09:04', null=True),
        ),
    ]
