# Generated by Django 2.2.24 on 2021-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210827_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id_log', models.AutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='info', max_length=2000, null=True)),
                ('time', models.DateTimeField(blank=True, db_column='time', default='2021-08-27 16:11:11', null=True)),
            ],
            options={
                'db_table': 'logger',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='LoggerTable',
        ),
    ]
