# Generated by Django 2.2.24 on 2021-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210827_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='parking_price_dol_max',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='parking_price_dol_min',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='parking_price_hrn_max',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='parking_price_hrn_min',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='parking_price_dol_max',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='parking_price_dol_min',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='parking_price_hrn_max',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='parking_price_hrn_min',
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='parking_price_dol_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='parking_price_dol_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='parking_price_hrn_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='parking_price_hrn_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_column='time', null=True),
        ),
    ]
