# Generated by Django 2.2.24 on 2021-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210829_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesandprices',
            name='ondate',
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesandprices',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
