# Generated by Django 2.2.24 on 2021-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210904_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesandprices',
            name='dollar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
