# Generated by Django 2.2.24 on 2021-09-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_salesandprices_dollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesandprices',
            old_name='avg_price_dol',
            new_name='avg_price',
        ),
        migrations.RenameField(
            model_name='salesandprices',
            old_name='avg_price_hrn',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='salesandprices',
            old_name='max_price_dol',
            new_name='min_price',
        ),
        migrations.RenameField(
            model_name='salesandprices',
            old_name='max_price_hrn',
            new_name='parking_price_max',
        ),
        migrations.RenameField(
            model_name='salesandprices',
            old_name='min_price_dol',
            new_name='parking_price_min',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='min_price_hrn',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='parking_price_dol_max',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='parking_price_dol_min',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='parking_price_hrn_max',
        ),
        migrations.RemoveField(
            model_name='salesandprices',
            name='parking_price_hrn_min',
        ),
    ]
