# Generated by Django 2.2.24 on 2021-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210904_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='commis_year',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='construction_phase_prst',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='parking_num',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='quarter',
            field=models.IntegerField(blank=True, db_column='Quarter', default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='houses',
            name='start_year',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='storeys',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='houses',
            name='ttl_area_apartments',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='ttl_area_building',
            field=models.FloatField(blank=True, default=''),
        ),
    ]
