# Generated by Django 2.2.24 on 2021-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210904_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='commis_year',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='start_year',
            field=models.TextField(blank=True),
        ),
    ]
