# Generated by Django 2.2.24 on 2021-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210904_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='street_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
