# Generated by Django 2.2.24 on 2021-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210904_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='start_work',
            field=models.CharField(blank=True, db_column='start_work', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
