# Generated by Django 2.2.24 on 2021-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210904_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='commis_year',
            field=models.CharField(blank=True, db_column='commis_year', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='start_year',
            field=models.CharField(blank=True, db_column='start_year', max_length=50, null=True),
        ),
    ]
