# Generated by Django 2.2.24 on 2021-09-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210904_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesAndPrices',
        ),
    ]
