# Generated by Django 2.2.24 on 2021-09-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_salesandprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAndPrices',
            fields=[
                ('id_row', models.AutoField(db_column='ID_row', primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('id_sections', models.ForeignKey(blank=True, db_column='ID_sections', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sections')),
            ],
            options={
                'db_table': 'sales_and_prices',
                'managed': True,
            },
        ),
    ]
